/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import civitas.CivitasJuego;
import civitas.Jugador;
import civitas.OperacionesJuego;
import civitas.SalidasCarcel;
import javax.swing.JOptionPane;

/**
 *
 * @author enriq
 */
public class CivitasView extends javax.swing.JFrame {

    CivitasJuego juegoModel;
    JugadorPanel jugadorPanel;
    GestionarDialog gestionarD;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add (jugadorPanel);
        gestionarD = new GestionarDialog(this, true);
        repaint();
        revalidate();
    }

    public void setCivitasJuego(CivitasJuego otro_juego){
        juegoModel = otro_juego;
        setVisible(true);
    }

    public void actualizarVista(){
        jugadorPanel.setJugador(juegoModel.getJugadorActual());
        infoCasilla.setText(juegoModel.getCasillaActual().toString());
        
        TextRanking.setVisible(false);
        
        if(juegoModel.finalDelJuego()){
            String ranking = "";
            
            for(int i = 0; i < juegoModel.ranking().size(); i++){
                ranking = ranking + i + "º - " + juegoModel.ranking().get(i).getNombre();
                ranking = ranking + "\n";
            }
            TextRanking.setText(ranking);
            TextRanking.setVisible(true);
        }
        
        repaint();
        revalidate();
    }
    
    public void mostrarSiguienteOperacion(OperacionesJuego siguiente){
        String operacion = " ";
        
        switch (siguiente) {
            case PASAR_TURNO:
                operacion = "Pasar turno";
                break;
            case COMPRAR:
                operacion = "Comprar";
                break;
            case GESTIONAR:
                operacion = "Gestionar";
                break;
            case SALIR_CARCEL:
                operacion = "Salir de la carcel";
                break;
            default:
                break;
        }
        
        infoSiguiente.setText(operacion);
        actualizarVista();
    }
    
    void mostrarEventos() {
        DiarioDialog diarioD= new DiarioDialog(this); //crea la ventana del diario
        diarioD.repaint();
        diarioD.revalidate();
        diarioD.setVisible(true);
    }
    
    Respuestas comprar(){
        int opcion= JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?","Compra", JOptionPane.YES_NO_OPTION);
        
        Respuestas respuesta;
        
        if(opcion == 1){
            respuesta = Respuestas.NO;
        }else{
            respuesta = Respuestas.SI;
        }
        
        return respuesta;
    }
    
    SalidasCarcel salirCarcel(){
        String[] opciones= {"Pagando", "Tirando"};
        int respuesta= JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?",
        "Salir de la cárcel", JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0] );
        
        return (SalidasCarcel.values()[respuesta]);
    }
    
    int getGestionElegida(){
        return gestionarD.getGestion();
    }
    
    int getPropiedadElegida(){
        return  gestionarD.getPropiedad();
    }
    
    void gestionar(Jugador jugador){
        gestionarD.gestionar(jugador);
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        Casilla_etiq = new javax.swing.JLabel();
        infoCasilla = new javax.swing.JTextField();
        SubtituloJugador_etiq = new javax.swing.JLabel();
        OperacionSiguiente_etiq = new javax.swing.JLabel();
        infoSiguiente = new javax.swing.JTextField();
        Ranking_etiq = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextRanking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titulo.setText("Civitas, El Juego");
        Titulo.setEnabled(false);

        Casilla_etiq.setText("Casilla:");

        infoCasilla.setText("infoCasilla");
        infoCasilla.setEnabled(false);
        infoCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCasillaActionPerformed(evt);
            }
        });

        SubtituloJugador_etiq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubtituloJugador_etiq.setText("JUGADOR");

        OperacionSiguiente_etiq.setText("Siguiente Operación:");

        infoSiguiente.setText("operacionSiguiente");
        infoSiguiente.setEnabled(false);
        infoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSiguienteActionPerformed(evt);
            }
        });

        Ranking_etiq.setText("Ranking:");

        TextRanking.setColumns(20);
        TextRanking.setRows(5);
        jScrollPane1.setViewportView(TextRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubtituloJugador_etiq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Ranking_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OperacionSiguiente_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Casilla_etiq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoCasilla))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 726, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(8, 8, 8)
                .addComponent(SubtituloJugador_etiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casilla_etiq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OperacionSiguiente_etiq)
                    .addComponent(infoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ranking_etiq))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCasillaActionPerformed

    private void infoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casilla_etiq;
    private javax.swing.JLabel OperacionSiguiente_etiq;
    private javax.swing.JLabel Ranking_etiq;
    private javax.swing.JLabel SubtituloJugador_etiq;
    private javax.swing.JTextArea TextRanking;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JTextField infoCasilla;
    private javax.swing.JTextField infoSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
