/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;

/**
 *
 * @author enriq
 */
public class JugadorPanel extends javax.swing.JPanel {

    Jugador jugador;
    
    
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    public void setJugador(Jugador otro_jugador){
        jugador = otro_jugador;
        String campo = "";
        
        infoNombre.setText(jugador.getNombre());
        campo = campo + jugador.getSaldo();
        infoSaldo.setText(campo);
        
        campo = "";
        if(jugador.isEncarcelado())
         campo = campo + "Sí";
        else
         campo = campo + "No";
        
        infoEncarcelado.setText(campo);
        
        campo = "";
        if(jugador.getCasasMax() != jugador.CasaMax)
         campo = campo + "Sí";
        else
         campo = campo + "No";
        
        infoEspeculador.setText(campo);
        repaint();
        
        rellenaPropiedades(jugador.getPropiedades());
    }
    
    private void rellenaPropiedades (ArrayList<TituloPropiedad> lista) {
        // Se elimina la información antigua
        propiedades.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_etiq = new javax.swing.JLabel();
        Saldo_etiq = new javax.swing.JLabel();
        Encarcelado_etiq = new javax.swing.JLabel();
        Especulador_etiq = new javax.swing.JLabel();
        infoNombre = new javax.swing.JTextField();
        infoSaldo = new javax.swing.JTextField();
        infoEncarcelado = new javax.swing.JTextField();
        infoEspeculador = new javax.swing.JTextField();
        SubitutloPropiedades_etiq = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        propiedades = new javax.swing.JPanel();

        setName(""); // NOI18N

        Nombre_etiq.setText("Nombre:");
        Nombre_etiq.setEnabled(false);

        Saldo_etiq.setText("Saldo:");
        Saldo_etiq.setEnabled(false);

        Encarcelado_etiq.setText("Encarcelado:");
        Encarcelado_etiq.setEnabled(false);

        Especulador_etiq.setText("Especulador:");
        Especulador_etiq.setEnabled(false);

        infoNombre.setText("Nombre");
        infoNombre.setEnabled(false);
        infoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNombreActionPerformed(evt);
            }
        });

        infoSaldo.setText("Saldo");
        infoSaldo.setEnabled(false);
        infoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSaldoActionPerformed(evt);
            }
        });

        infoEncarcelado.setText("Encarcelado");
        infoEncarcelado.setEnabled(false);
        infoEncarcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEncarceladoActionPerformed(evt);
            }
        });

        infoEspeculador.setText("Especulador");
        infoEspeculador.setEnabled(false);

        SubitutloPropiedades_etiq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubitutloPropiedades_etiq.setText("PROPIEDADES");

        jScrollPane1.setViewportView(propiedades);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Encarcelado_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Especulador_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Saldo_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubitutloPropiedades_etiq))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_etiq)
                    .addComponent(infoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Saldo_etiq)
                    .addComponent(infoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Encarcelado_etiq, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Especulador_etiq)
                        .addComponent(infoEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(SubitutloPropiedades_etiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void infoEncarceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEncarceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoEncarceladoActionPerformed

    private void infoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoSaldoActionPerformed

    private void infoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encarcelado_etiq;
    private javax.swing.JLabel Especulador_etiq;
    private javax.swing.JLabel Nombre_etiq;
    private javax.swing.JLabel Saldo_etiq;
    private javax.swing.JLabel SubitutloPropiedades_etiq;
    private javax.swing.JTextField infoEncarcelado;
    private javax.swing.JTextField infoEspeculador;
    private javax.swing.JTextField infoNombre;
    private javax.swing.JTextField infoSaldo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel propiedades;
    // End of variables declaration//GEN-END:variables
}
