/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author enriq
 */
public class PropiedadPanel extends javax.swing.JPanel {

    TituloPropiedad tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    void setPropiedad( TituloPropiedad titulo){
        tituloPropiedad = titulo;
        String campo = "";
        infoNombre.setText(titulo.getNombre());
        campo = campo + titulo.getNumCasas();
        infoNumCasas.setText(campo);
        campo = "" + titulo.getNumHoteles();
        infoNumHoteles.setText(campo);
        campo = "" + titulo.getHipotecado();
        infoHipotecada.setText(campo);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_etiq = new javax.swing.JLabel();
        Casas_etiq = new javax.swing.JLabel();
        Hoteles_etiq = new javax.swing.JLabel();
        Hipotecado_etiq = new javax.swing.JLabel();
        infoNombre = new javax.swing.JTextField();
        infoNumCasas = new javax.swing.JTextField();
        infoNumHoteles = new javax.swing.JTextField();
        infoHipotecada = new javax.swing.JTextField();

        Nombre_etiq.setText("Nombre:");
        Nombre_etiq.setEnabled(false);

        Casas_etiq.setText("Casas:");
        Casas_etiq.setEnabled(false);

        Hoteles_etiq.setText("Hoteles:");
        Hoteles_etiq.setEnabled(false);

        Hipotecado_etiq.setText("Hipotecada:");
        Hipotecado_etiq.setEnabled(false);

        infoNombre.setText("Nombre");
        infoNombre.setEnabled(false);
        infoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNombreActionPerformed(evt);
            }
        });

        infoNumCasas.setText("numCasas");
        infoNumCasas.setEnabled(false);
        infoNumCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNumCasasActionPerformed(evt);
            }
        });

        infoNumHoteles.setText("numHoteles");
        infoNumHoteles.setEnabled(false);
        infoNumHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNumHotelesActionPerformed(evt);
            }
        });

        infoHipotecada.setText("hipotecada");
        infoHipotecada.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Nombre_etiq)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(infoNombre))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Casas_etiq)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(infoNumCasas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hoteles_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoNumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hipotecado_etiq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoHipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_etiq)
                    .addComponent(infoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casas_etiq)
                    .addComponent(infoNumCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hoteles_etiq)
                    .addComponent(infoNumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hipotecado_etiq)
                    .addComponent(infoHipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void infoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNombreActionPerformed

    private void infoNumCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNumCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNumCasasActionPerformed

    private void infoNumHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNumHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNumHotelesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casas_etiq;
    private javax.swing.JLabel Hipotecado_etiq;
    private javax.swing.JLabel Hoteles_etiq;
    private javax.swing.JLabel Nombre_etiq;
    private javax.swing.JTextField infoHipotecada;
    private javax.swing.JTextField infoNombre;
    private javax.swing.JTextField infoNumCasas;
    private javax.swing.JTextField infoNumHoteles;
    // End of variables declaration//GEN-END:variables
}
